### ISSUE TITLE
Unable to change backgroundBarColor

### ISSUE THREAD

**Issue by Seferi** [ajomuch92/flutter-bottom-sheet-expandable-bar#1]
Hi mate,

I'm trying to change the background color of the bar but unable to. Here is the relevant part of the color:
`bottomSheet: BottomBarSheet(backgroundBarColor: Colors.lightBlueAccent,
        buttonPosition: ButtonBottomBarPosition.center,
        innerChild: Center(
          child: Text('Bottom sheet'),
        ),
        currentIndex: _currentIndex,
        curve: Curves.bounceIn,
        children: [
          BottomSheetBarIcon(
            icon: Icon(Icons.home),
            color: Colors.redAccent,
            onTap: () {
              setState(() {
                _currentIndex = 0;
              });
            },
          ),`

**Comment by ajomuch92** [comment]
Hello @Seferi, let me check this issue to upload a new version, just give me some time to review it

**Comment by ajomuch92** [comment]
I released a [new version](https://pub.dev/packages/bottom_sheet_expandable_bar/versions/0.1.2) to fix this bug. Please check the example on this repository. Thanks @Seferi for noticing this bug

**Comment by Seferi** [comment]
Thanks for the quick respons and the fix mate!
